import { Geist, Geist_Mono } from "next/font/google";
import localFont from 'next/font/local'
import "./globals.css";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: {
    default: "Rafs Artworks",
    template: '%s | Rafs Artworks'
  },
  description: "Generated by create next app",
};

export const testFont = localFont({
  src: './../fonts/ShortBaby-Mg2w.ttf',
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="min-h-screen flex flex-col">
          <Navbar></Navbar>
          <main className="flex-1">
            {children}
          </main>
          <Footer></Footer>
        </div>
      </body>
    </html>
  );
}
